import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">

        <nav className="w-full flex justify-between p-4 border-b border-gray-200">
  <a href="/">Home</a>
  <div className="flex gap-4">
    <a href="/auth/login">Login</a>
    <a href="/auth/signup">Signup</a>
    <a href="/profile">Profile</a>
  </div>
</nav>
        
{children}
      
      </body>
    </html>
  );
}
